# Site settings
title: Learning to Blog
header-img: img/home-bg.png
email: ozziepopovas@gmail.com
copyright_name: ozPop
description: > # this means to ignore newlines until "baseurl:"
  Getting my blogggin feet wet
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  ozPop
learn_profile: ozPop
email_username: ozziepopovas@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
